/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:68a6885d-c069-4a46-85a5-09d3360e7888",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_ZiB8rtbwK",
    "aws_user_pools_web_client_id": "eko38puhga5dqstml0s4695l0",
    "oauth": {}
};


export default awsmobile;
